import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/quant': 'http://localhost:8001',
      '/m18': 'http://localhost:8001',
      '/research': 'http://localhost:8001',
      '/system': 'http://localhost:8001',
      '/market': 'http://localhost:8001',
      '/portfolios': 'http://localhost:8001',
      '/watchlists': 'http://localhost:8001',
      '/copilot': 'http://localhost:8001',
      '/alternative-data': 'http://localhost:8001',
      '/multi-asset': 'http://localhost:8001',
      '/events': 'http://localhost:8001',
      '/trading': 'http://localhost:8001',
      '/observability': 'http://localhost:8001',
      '/portfolio-optimization': 'http://localhost:8001',
      '/alt-intelligence': 'http://localhost:8001',
      '/analytics': 'http://localhost:8001',
      '/orchestrator': 'http://localhost:8001',
      '/health': 'http://localhost:8001',
      '/auth': 'http://localhost:8001',
      '/notifications': 'http://localhost:8001',
      '/market-intel': 'http://localhost:8001',
      '/knowledge-graph': 'http://localhost:8001',
      '/economic-calendar': 'http://localhost:8001',
      '/options': 'http://localhost:8001',
      '/agents': 'http://localhost:8001',
      '/brokers': 'http://localhost:8001',
      '/documents': 'http://localhost:8001',
      '/executions': 'http://localhost:8001',
      '/market-data': 'http://localhost:8001',
      '/news': 'http://localhost:8001',
      '/orders': 'http://localhost:8001',
      '/paper': 'http://localhost:8001',
      '/reports': 'http://localhost:8001',
      '/screeners': 'http://localhost:8001',
      '/trading-alerts': 'http://localhost:8001',
      '/workspace': 'http://localhost:8001',
      '/execution': 'http://localhost:8001',
      '/providers': 'http://localhost:8001',
      '/knowledge': 'http://localhost:8001',
      '/backtest': 'http://localhost:8001',
    },
  },
  build: {
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-query': ['@tanstack/react-query', '@tanstack/react-query-devtools'],
          'vendor-charts': ['recharts', 'lightweight-charts'],
          'vendor-http': ['axios'],
          'vendor-state': ['zustand'],
        },
      },
    },
  },
})
