"""add_research_tables

Revision ID: 6ac7d66f1369
Revises: f99d32d86938
Create Date: 2026-06-27 19:04:16.754236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ac7d66f1369'
down_revision: Union[str, Sequence[str], None] = 'f99d32d86938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('benchmark', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('position_size_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annual_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtests_created_at', 'backtests', ['created_at'], unique=False)
    op.create_index('ix_backtests_ticker', 'backtests', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtests_ticker', table_name='backtests')
    op.drop_index('ix_backtests_created_at', table_name='backtests')
    op.drop_table('backtests')
    op.drop_table('strategies')
    # ### end Alembic commands ###
