"""add_trading_tables

Revision ID: 84ebaa12585a
Revises: 8e9b825d94cc
Create Date: 2026-06-27 23:09:08.403398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84ebaa12585a'
down_revision: Union[str, Sequence[str], None] = '8e9b825d94cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.Enum('PAPER', 'ALPACA', 'IBKR', 'BINANCE', 'KRAKEN', 'OANDA', 'POLYGON', name='broker_type_enum', create_constraint=True), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'CONNECTING', 'ERROR', name='broker_status_enum', create_constraint=True), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission_type', sa.Enum('FLAT', 'PER_SHARE', 'PERCENT', name='commission_type_enum', create_constraint=True), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('min_commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('slippage_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.Enum('ORDER_FILLED', 'ORDER_REJECTED', 'MARGIN_WARNING', 'RISK_LIMIT', 'PORTFOLIO_LIMIT', 'DRAWDOWN_ALERT', 'PNL_ALERT', 'POSITION_LIMIT', 'PRICE_ALERT', name='alert_type_enum', create_constraint=True), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('paper_account_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('trigger_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_portfolio', 'alerts', ['portfolio_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('paper_account_id', sa.UUID(), nullable=True),
    sa.Column('broker_connection_id', sa.UUID(), nullable=True),
    sa.Column('basket_id', sa.UUID(), nullable=True),
    sa.Column('parent_order_id', sa.UUID(), nullable=True),
    sa.Column('linked_order_id', sa.UUID(), nullable=True),
    sa.Column('link_type', sa.Enum('NONE', 'BRACKET_PARENT', 'BRACKET_PROFIT', 'BRACKET_STOP', 'OCO_PRIMARY', 'OCO_SECONDARY', 'OTO_TRIGGER', 'OTO_SECONDARY', name='link_type_enum', create_constraint=True), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP', 'BRACKET', 'OCO', 'OTO', name='order_type_enum', create_constraint=True), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'SELL_SHORT', 'BUY_TO_COVER', name='order_side_enum', create_constraint=True), nullable=False),
    sa.Column('time_in_force', sa.Enum('DAY', 'GTC', 'IOC', 'FOK', name='time_in_force_enum', create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trail_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trail_type', sa.Enum('AMOUNT', 'PERCENT', name='trail_type_enum', create_constraint=True), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exec_algo', sa.Enum('NONE', 'TWAP', 'VWAP', 'POV', 'ICEBERG', 'ARRIVAL', 'ADAPTIVE', name='exec_algo_enum', create_constraint=True), nullable=False),
    sa.Column('exec_algo_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='order_status_enum', create_constraint=True), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('estimated_commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_slippage', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('strategy_tag', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_basket', 'orders', ['basket_id'], unique=False)
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_paper_account_id'), 'orders', ['paper_account_id'], unique=False)
    op.create_index('ix_orders_paper_account_status', 'orders', ['paper_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index('ix_orders_portfolio_status', 'orders', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_orders_ticker_created', 'orders', ['ticker', 'created_at'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_account_id'), 'paper_positions', ['account_id'], unique=False)
    op.create_index('ix_paper_positions_account_ticker', 'paper_positions', ['account_id', 'ticker'], unique=True)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_price_at_fill', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('venue', sa.String(length=50), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_index('ix_executions_order_time', 'executions', ['order_id', 'execution_time'], unique=False)
    op.create_index('ix_executions_ticker_time', 'executions', ['ticker', 'execution_time'], unique=False)
    op.create_table('order_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'VALIDATED', 'SUBMITTED', 'ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'MODIFIED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'REJECTED', 'EXPIRED', 'SIMULATION', name='audit_event_enum', create_constraint=True), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_order_created', 'order_audit_log', ['order_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_audit_log_order_id'), 'order_audit_log', ['order_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_price_at_fill', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('slippage_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('strategy_tag', sa.String(length=100), nullable=True),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_account_id'), 'paper_trades', ['account_id'], unique=False)
    op.create_index('ix_paper_trades_account_time', 'paper_trades', ['account_id', 'trade_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_trades_account_time', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_account_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_order_audit_log_order_id'), table_name='order_audit_log')
    op.drop_index('ix_audit_log_order_created', table_name='order_audit_log')
    op.drop_table('order_audit_log')
    op.drop_index('ix_executions_ticker_time', table_name='executions')
    op.drop_index('ix_executions_order_time', table_name='executions')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_paper_positions_account_ticker', table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_account_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index('ix_orders_ticker_created', table_name='orders')
    op.drop_index('ix_orders_portfolio_status', table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_index('ix_orders_paper_account_status', table_name='orders')
    op.drop_index(op.f('ix_orders_paper_account_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_index('ix_orders_basket', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_alerts_portfolio', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('paper_accounts')
    op.drop_table('broker_connections')
    # ### end Alembic commands ###
