"""add_analytics_tables

Revision ID: 8e9b825d94cc
Revises: 6ac7d66f1369
Create Date: 2026-06-27 20:19:01.269040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e9b825d94cc'
down_revision: Union[str, Sequence[str], None] = '6ac7d66f1369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stress_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_optimizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('expected_volatility', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('frontier_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_optimizations_portfolio_id'), 'portfolio_optimizations', ['portfolio_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('holdings_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('daily_return_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('risk_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('var_historical_95', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('var_parametric_95', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('var_monte_carlo_95', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility_annual', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_analyses_portfolio_id'), 'risk_analyses', ['portfolio_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('simulation_days', sa.Integer(), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('initial_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percentile_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_value_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prob_loss', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_final_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_portfolio_id'), 'simulation_results', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_results_portfolio_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_risk_analyses_portfolio_id'), table_name='risk_analyses')
    op.drop_table('risk_analyses')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_optimizations_portfolio_id'), table_name='portfolio_optimizations')
    op.drop_table('portfolio_optimizations')
    op.drop_table('stress_scenarios')
    # ### end Alembic commands ###
